name: Build and Push to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'noc-api/**'
      - 'noc-app/**'
      - .github/workflows/deploy-ops.yml
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: ${{ github.repository }}-ops-api
  IMAGE_NAME_APP: ${{ github.repository }}-painel-web

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push API
      - name: Extract metadata (tags, labels) for API
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./noc-api
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

      # Build & Push App
      - name: Extract metadata (tags, labels) for App
        id: meta-app
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_APP }}

      - name: Build and push App Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./noc-app
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}
